### ISSUE TITLE
TypeError: a bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by kamankam** [HAShihab/fathmm-MKL#3]
Hi everyone!
 I am using fathmm-MKL with test data with  following command:
`python fathmm-MKL.py test.txt out-test fathmm-MKL_Current_zerobased.tab.gz`

As a result  I get following error:
`Traceback (most recent call last):
  File "fathmm-MKL.py", line 90, in <module>
    for record in data.split("\n"):
TypeError: a bytes-like object is required, not 'str'`

What needs to be done to successfully launch the program?

Thank you
Katya

**Comment by t0mrg** [comment]
We have updated the code to work with Python 3, so this error should now not occur with the command you used. 

**Further details:**

This error probably occurred because fathmm-MKL.py was written for Python version 2 (the primary version at the time this was written). The error you saw would happen if you attempted to run the script with Python version 3, which introduced some language changes. 

(On most systems Python 2 is still available, so the command ```python2.7 fathmm-MKL.py test.txt out-test fathmm-MKL_Current_zerobased.tab.gz``` should have worked.)
